### ISSUE TITLE
Jenkins and Docker - cannot build.

### ISSUE THREAD

**Issue by hjortronet72** [IARSystems/bxarm-jenkins#1]
I followed the instructions (https://github.com/IARSystems/bxarm-docker) and created a Docker image but I'm not able to build anything on Jenkins. Any thoughts?

**Comment by felipe-iar** [comment]
Hi @hjortronet72 

Thank you for your question.
There are aspects that should be taken into consideration when creating a Docker Image for Jenkins-specific use.
We have a new entry on the [bxarm-jenkins wiki](https://github.com/IARSystems/bxarm-jenkins/wiki) which delineates such requirements.

* [Creating a BXARM-Docker image for Jenkins](https://github.com/IARSystems/bxarm-jenkins/wiki/creating-a-bxarm-docker-image-for-jenkins)
